{{- $addonValues := default dict .Values.addonValues -}}
{{- $sealedSecretsAddon := default dict (index $addonValues "sealedSecretsAddon") -}}
{{- $addonParameters := default dict (index $sealedSecretsAddon "addonParameters") -}}
{{- $valuesObject := default dict (index $sealedSecretsAddon "valuesObject") -}}
{{- if and $valuesObject.ingress.enabled (not (empty $valuesObject.ingress.host)) }}
{{- $managmentCluster := .Values.addonValues.cluster.name -}}
{{- $destinationNamespace := .Values.destination.namespace }}
{{- $destinationServer := .Values.destination.server }}
{{- $shouldMirrorSecret := $addonParameters.mirrorSecretsToAllClusters }}
{{- $shouldCreateSecretsApp := and $mirrorSecretsToAllClusters $sealedSecretsAddon.enabled  }}
{{- if $shouldCreateSecretsApp }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-secrets-{{ $managmentCluster }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-admin
  source:
    repoURL: https://koalaops.github.io/koala-addons
    targetRevision: 0.1.0
    chart: yaml-to-manifest
    helm:
      releaseName: "sealed-secrets-secrets-{{ $managmentCluster }}"
      valuesObject: 
        manifests:
        {{- if $shouldMirrorSecret  }}
        {{- $sealedSecretName := $valuesObject.sealedsecrets.secretName}}
        {{- $sealedSecretKey := include "chart.findSecretByPrefixAndLabel" (dict "desiredPrefix" $sealedSecretName $destinationNamespace .Release.Namespace) -}}
        {{- $tlsCert := index $sealedSecretKey "data" "tls.crt" }}
        {{- $tlsKey := index $sealedSecretKey "data" "tls.key" }}
          - apiVersion: v1
            kind: Secret
            metadata:
              name: {{ $sealedSecretName}}-test
              namespace: {{ $destinationNamespace}}
              annotations:
                argocd.argoproj.io/compare-options: IgnoreExtraneous
            data:
              tls.crt: {{ $tlsCert | b64enc | quote }}
              tls.key: {{ $tlsKey  | b64enc | quote }}
        {{- range $key, $cluster := .Values.addonValues.clusters }}
          - apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: sealed-secrets-mirror-secrets-{{ $cluster.name }}
              namespace: argocd
              finalizers:
                - resources-finalizer.argocd.argoproj.io
            spec:
              project: cluster-admin
              source:
                repoURL: https://koalaops.github.io/koala-addons
                targetRevision: 0.1.0
                chart: yaml-to-manifest
                helm:
                  releaseName: "sealed-secrets-secrets-{{ $managmentCluster }}"
                  valuesObject: 
                    manifests:
                      - apiVersion: v1
                        kind: Secret
                        metadata:
                          name: {{ $sealedSecretName }}
                          namespace: {{ $destinationNamespace}}
                          annotations:
                            argocd.argoproj.io/compare-options: IgnoreExtraneous
                        data:
                          tls.crt: {{ $tlsCert | b64enc | quote }}
                          tls.key: {{ $tlsKey  | b64enc | quote }}
              destination:
                server: {{ $cluster.address}}
                namespace: {{ $destinationNamespace}}
              syncPolicy:
                syncOptions:
                  - CreateNamespace=true
                automated:
                  prune: true
                  selfHeal: true
                  allowEmpty: true
        {{- end}}
        {{- end }}
  destination:
    server: {{ $destinationServer }}
    namespace: {{ $destinationNamespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
{{- end }}
{{- end }}