name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # - name: Add observability repositories
      #   working-directory: charts/observability-opensource-complete
      #   run: |
      #     helm repo add grafana https://grafana.github.io/helm-charts
      #     helm repo add opentelemetry https://open-telemetry.github.io/opentelemetry-helm-charts
      #     helm repo update
      #     helm dependency update
      #     helm dependency build

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        # with:
        #   charts_dir: argo-apps
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
