{{- $addonValues := default dict .Values.addonValues -}}
{{- $grafanaTempoAddon := default dict (index $addonValues "grafanaTempoAddon") -}}
{{- $addonParameters := default dict (index $grafanaTempoAddon "addonParameters") -}}
{{- $valuesObject := default dict (index $grafanaTempoAddon "valuesObject") -}}
{{- if and $valuesObject.ingress.enabled (not (empty $valuesObject.ingress.host)) }}
{{- $managmentCluster := .Values.addonValues.cluster.name -}}
{{- $destinationNamespace := .Values.destination.namespace }}
{{- $destinationServer := .Values.destination.server }}
{{- $shouldGenerateSceret := $addonParameters.createSecrets }}
{{- $shouldMirrorSecret := $addonParameters.mirrorSecretsToAllClusters }}
{{- $shouldCreateSecretsApp := and $shouldGenerateSceret $grafanaTempoAddon.enabled  }}
{{- if $shouldCreateSecretsApp }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-tempo-secrets-{{ $managmentCluster }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-admin
  source:
    repoURL: https://koalaops.github.io/koala-addons
    targetRevision: 0.1.0
    chart: yaml-to-manifest
    helm:
      releaseName: "grafana-tempo-secrets-{{ $managmentCluster }}"
      valuesObject: 
        manifests:
        {{- $tempoUsername:= include "tempo.username" .}}
        {{- $tempoPassword:= "ac992f09-c175-4883-be8d-f7ae5fa710d0"}}
        {{- $tempoAuthForIngress:=  printf "%s:$apr1$OhXMLDG4$BEpU8S8T2.ig0fk/n9fiO1" $tempoUsername  }}
        {{- $tempoAuthClient:= printf "%s:%s" $tempoUsername $tempoPassword  }}
        {{- if $shouldGenerateSceret }}
          - apiVersion: v1
            kind: Secret
            metadata:
              name: {{ include "sourceAuthSecretName" $ }}
              namespace: {{ $destinationNamespace}}
              annotations:
                argocd.argoproj.io/compare-options: IgnoreExtraneous
            data:
              username: {{ $tempoUsername | b64enc | quote }}
              password: {{ $tempoPassword | b64enc | quote }}
              auth: {{  $tempoAuthForIngress | b64enc | quote }}
              auth-client: {{ $tempoAuthClient | b64enc | b64enc | quote }}
        {{- end }}
        {{- if $shouldMirrorSecret  }}
          - apiVersion: v1
            kind: Secret
            metadata:
              name: {{ include "authSecretName" $ }}
              namespace: {{ $destinationNamespace}}
              annotations:
                argocd.argoproj.io/compare-options: IgnoreExtraneous
            data:
              username: {{ $tempoUsername | b64enc | quote }}
              password: {{ $tempoPassword  | b64enc | quote }}
              auth: {{  $tempoAuthForIngress | b64enc | quote }}
              auth-client: {{ $tempoAuthClient | b64enc | b64enc | quote }}
        {{- range $key, $cluster := $valuesObject.secretsInClusters }}
          - apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: tempo-mirror-secrets-{{ $cluster.name }}
              namespace: argocd
              finalizers:
                - resources-finalizer.argocd.argoproj.io
            spec:
              project: cluster-admin
              source:
                repoURL: https://koalaops.github.io/koala-addons
                targetRevision: 0.1.0
                chart: yaml-to-manifest
                helm:
                  releaseName: "grafana-tempo-secrets-{{ $managmentCluster }}"
                  valuesObject: 
                    manifests:
                      - apiVersion: v1
                        kind: Secret
                        metadata:
                          name: {{ include "authSecretName" $ }}
                          namespace: {{ $destinationNamespace}}
                          annotations:
                            argocd.argoproj.io/compare-options: IgnoreExtraneous
                        data:
                          username: {{ $tempoUsername | b64enc | quote }}
                          password: {{ $tempoPassword | b64enc | quote }}
                          auth: {{  $tempoAuthForIngress | b64enc | quote }}
                          auth-client: {{ $tempoAuthClient | b64enc | b64enc | quote }}
              destination:
                server: {{ $cluster.address}}
                namespace: {{ $destinationNamespace}}
              syncPolicy:
                syncOptions:
                  - CreateNamespace=true
                automated:
                  prune: true
                  selfHeal: true
                  allowEmpty: true
        {{- end}}
        {{- end }}
  destination:
    server: {{ $destinationServer }}
    namespace: {{ $destinationNamespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
{{- end }}
{{- end }}